In [1]:
import pandas as pd

In [2]:
# Task 1.1
books = pd.DataFrame({
    "Title": [
        "1984",
        "To Kill a Mockingbird",
        "Clean Code",
        "The Pragmatic Programmer",
        "Atomic Habits",
        "Designing Data-Intensive Applications",
    ],
    "Author": [
        "George Orwell",
        "Harper Lee",
        "Robert C. Martin",
        "Andrew Hunt & David Thomas",
        "James Clear",
        "Martin Kleppmann",
    ],
    "PublicationYear": [1949, 1960, 2008, 1999, 2018, 2017],
    "Price": [9.99, 12.50, 34.99, 39.99, 16.99, 44.99],
})

In [3]:
# Task 1.2
books

,Title,Author,PublicationYear,Price
0,1984,George Orwell,1949,9.99
1,To Kill a Mockingbird,Harper Lee,1960,12.50
2,Clean Code,Robert C. Martin,2008,34.99
3,The Pragmatic Programmer,Andrew Hunt & David Thomas,1999,39.99
4,Atomic Habits,James Clear,2018,16.99
5,Designing Data-Intensive Applications,Martin Kleppmann,2017,44.99

In [4]:
# Task 1.3
books["Price"].mean()

np.float64(26.575)

In [5]:
# Task 1.4
books[books["PublicationYear"] > 2015]

,Title,Author,PublicationYear,Price
4,Atomic Habits,James Clear,2018,16.99
5,Designing Data-Intensive Applications,Martin Kleppmann,2017,44.99

In [6]:
# Task 1.5
books.sort_values("Price")

,Title,Author,PublicationYear,Price
0,1984,George Orwell,1949,9.99
1,To Kill a Mockingbird,Harper Lee,1960,12.50
4,Atomic Habits,James Clear,2018,16.99
2,Clean Code,Robert C. Martin,2008,34.99
3,The Pragmatic Programmer,Andrew Hunt & David Thomas,1999,39.99
5,Designing Data-Intensive Applications,Martin Kleppmann,2017,44.99

In [7]:
# Task 2.1
orders = pd.read_csv("./data/orders.csv")

In [8]:
# Task 2.2
orders.head(10)

   OrderID Customer        Date  Amount
0        1      Ali  2024-01-02     100
1        2     Vali  2024-01-03     250
2        3      Ali  2024-01-05      80
3        4    Leyla  2024-01-06     300
4        5     Vali  2024-01-08     150
5        6    Nigar  2024-01-09      90
6        7      Ali  2024-01-11     200
7        8    Leyla  2024-01-12     400
8        9    Nigar  2024-01-14     120
9       10     Vali  2024-01-15      60

In [9]:
# Task 2.3
orders.groupby("Customer")["OrderID"].count()

Customer
Ali      5
Leyla    3
Nigar    3
Vali     4
Name: OrderID, dtype: int64

In [10]:
# Task 2.4
orders["Amount"].max(), orders["Amount"].min()

(np.int64(400), np.int64(60))

In [11]:
# Task 2.5
orders["Amount"].sum()

np.int64(2675)

In [12]:
# Task 3.1
food = pd.DataFrame({
    "Product": ["Apple", "Chicken Breast", "Bread", "Milk", "Cheese","Walnuts", "Rice", "Salmon", "Egg", "Olive Oil"],
    "Category": ["Fruit", "Meat", "Grain", "Dairy", "Dairy","Nuts", "Grain", "Meat", "Dairy", "Oil"],
    "Calories": [52, 239, 265, 42, 402, 654, 130, 206, 155, 884],
    "Protein": [0.3, 27, 9, 3.4, 25, 15, 2.7, 22, 13, 0]
})

In [13]:
# Task 3.2
food

          Product Category  Calories  Protein
0           Apple    Fruit        52      0.3
1  Chicken Breast     Meat       239     27.0
2           Bread    Grain       265      9.0
3            Milk    Dairy        42      3.4
4          Cheese    Dairy       402     25.0
5         Walnuts     Nuts       654     15.0
6            Rice    Grain       130      2.7
7          Salmon     Meat       206     22.0
8             Egg    Dairy       155     13.0
9       Olive Oil      Oil       884      0.0

In [14]:
# Task 3.3
food[food["Calories"] > 300]

     Product Category  Calories  Protein
4     Cheese    Dairy       402     25.0
5    Walnuts     Nuts       654     15.0
9  Olive Oil      Oil       884      0.0

In [15]:
# Task 3.4
food.groupby("Category")["Protein"].mean()

Category
Dairy    13.80
Fruit     0.30
Grain     5.85
Meat     24.50
Nuts     15.00
Oil       0.00
Name: Protein, dtype: float64

In [16]:
# Task 3.5
food.sort_values("Calories", ascending=False)

          Product Category  Calories  Protein
9       Olive Oil      Oil       884      0.0
5         Walnuts     Nuts       654     15.0
4          Cheese    Dairy       402     25.0
2           Bread    Grain       265      9.0
1  Chicken Breast     Meat       239     27.0
7          Salmon     Meat       206     22.0
8             Egg    Dairy       155     13.0
6            Rice    Grain       130      2.7
0           Apple    Fruit        52      0.3
3            Milk    Dairy        42      3.4

In [17]:
# Task 4.1
work = pd.DataFrame({
    "Name": ["Ali", "Vali", "Ali", "Leyla", "Vali", "Nigar", "Ali", "Leyla"],
    "Project": [
        "Website Redesign", "Website Redesign", "Mobile App", "Mobile App",
        "Mobile App", "Website Redesign", "Database Migration", "Database Migration",
    ],
    "Hours": [8, 6, 5, 7, 4, 9, 6, 5],
})

In [18]:
# Task 4.2
work

    Name             Project  Hours
0    Ali    Website Redesign      8
1   Vali    Website Redesign      6
2    Ali          Mobile App      5
3  Leyla          Mobile App      7
4   Vali          Mobile App      4
5  Nigar    Website Redesign      9
6    Ali  Database Migration      6
7  Leyla  Database Migration      5

In [19]:
# Task 4.3
work.groupby("Name")["Hours"].sum()

Name
Ali      19
Leyla    12
Nigar     9
Vali     10
Name: Hours, dtype: int64

In [20]:
# Task 4.4
work.groupby("Project")["Hours"].sum()

Project
Database Migration    11
Mobile App            16
Website Redesign      23
Name: Hours, dtype: int64

In [21]:
# Task 4.5
work.groupby("Name")["Hours"].sum().idxmax()

'Ali'

In [22]:
# Task 5.1
tickets = pd.DataFrame({
    "Movie": ["Movie A", "Movie B", "Movie A", "Movie C", "Movie B", "Movie A","Movie C", "Movie B", "Movie A", "Movie C", "Movie B", "Movie A"],
    "City": ["Baku", "Ganja", "Sumgait", "Baku", "Baku", "Ganja","Sumgait", "Sumgait", "Baku", "Ganja", "Baku", "Sumgait"],
    "TicketsSold": [120, 80, 95, 60, 150, 70, 40, 110, 200, 55, 130, 90],
})

In [23]:
# Task 5.2
tickets

      Movie     City  TicketsSold
0   Movie A     Baku          120
1   Movie B    Ganja           80
2   Movie A  Sumgait           95
3   Movie C     Baku           60
4   Movie B     Baku          150
5   Movie A    Ganja           70
6   Movie C  Sumgait           40
7   Movie B  Sumgait          110
8   Movie A     Baku          200
9   Movie C    Ganja           55
10  Movie B     Baku          130
11  Movie A  Sumgait           90

In [24]:
# Task 5.3
tickets.groupby("Movie")["TicketsSold"].sum()

Movie
Movie A    575
Movie B    470
Movie C    155
Name: TicketsSold, dtype: int64

In [25]:
# Task 5.4
tickets.groupby("City")["TicketsSold"].sum()

City
Baku       660
Ganja      205
Sumgait    335
Name: TicketsSold, dtype: int64

In [26]:
# Task 5.5
tickets.groupby("Movie")["TicketsSold"].sum().idxmax()

'Movie A'